server:
  port: 8080

#spring properties
spring:
  #application
  application:
    name: USER_SERVICE

  config:
    import: "optional:configserver:http://localhost:9023/"


 #h2 database
 h2:
   console:
     enabled: true
 sql:
   init:
     platform: h2
 datasource:
   url: jdbc:h2:mem:user
 jpa:
   hibernate:
     ddl-auto=update: update

#eureka
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:9090/eureka/
